moved and improved guidelines form solid-ui
SolidOS/solidos pull request #158
Opened 2022-04-21 15:06 UTC by theRealImy

Here are the copied over (and improved) guidelines for coding and testing. -> @SharonStrats, @angelo-v what do you think about the testing?
The new one is the one on dependencies and releases. -> @bourgeoa what do you think?

2022-04-21 15:11 UTC, theRealImy commented
As follow up: also a wiki page updated was done at https://github.com/SolidOS/solidos/wiki/SolidOS-documentation
And the according files were deleted in solid-ui (see: https://github.com/SolidOS/solid-ui/commit/0511f5d1f6fe759f7396dec358c26e789382e544)

2022-04-21 15:31 UTC, TallTed commented on README.md
>  ```
```suggestion
_**🌟🌟🌟 SolidOS is an Operating System for Solid. 🌟🌟🌟**_
```

2022-04-21 15:32 UTC, TallTed commented on README.md
> +For a longe-term roadmap, we use a [Solid task manager](https://solidos.solidcommunity.net/public/Roadmap/Tasks/), and plan the next milestones on Kanban.
```suggestion
For a longer-term roadmap, we use a [Solid task manager](https://solidos.solidcommunity.net/public/Roadmap/Tasks/), and plan the next milestones on Kanban.
```

2022-04-21 15:34 UTC, TallTed commented on README.md
> +***Note:*** Please get familiar with [release guidelines](./documentation/guidelines/dependencies_and_release_guidelines.md).
```suggestion
There is a process and code in place to help with SolidOS releases. However, we would like to get better and automate as much as possible. Open issues can be found on the [Project Board](https://github.com/orgs/SolidOS/projects/1/views/4) under the CI category. 

_**Note:** Please get familiar with [release guidelines](./documentation/guidelines/dependencies_and_release_guidelines.md)._
```

2022-04-22 17:35 UTC, chunt007 reviewed
Git Bash https://gitforwindows.org/ for those trying to run bash scripts on their Windows machines. It requires a bit of configuration, but not too difficult.
Cygin library may be needed
https://www.cygwin.com/ Library may be needed as well.

or

Windows Subsystem for Linux.
https://docs.microsoft.com/en-us/windows/wsl/about as well.

2022-04-26 11:00 UTC, angelo-v commented on documentation/guidelines/coding_guidelines.md
> +This is a document about coding guidelines and processes. These topics reflect the way SolidOS stack conotributors work.
```suggestion
This is a document about coding guidelines and processes. These topics reflect the way SolidOS stack contributors work.
```

2022-04-26 14:37 UTC, TallTed commented on README.md
> +To check possible tasks you can help with immediately, look on the [Newcomer View in the Project Board](https://github.com/orgs/SolidOS/projects/1/views/3). You are welcome to visit us on a [weekly t
```suggestion
To check for tasks you might help with immediately, look at the [Newcomer View in the Project Board](https://github.com/orgs/SolidOS/projects/1/views/3). You are welcome to visit us at a [weekly team meeting](https://solidos.solidcommunity.net/Team/2021/schedule/solidos-schedule.html) or on the [ongoing Gitter-based chat](https://gitter.im/solid/solidos) to say 'Hi' or let us know about any blocker you might have encountered.
```

2022-04-26 14:38 UTC, TallTed commented on README.md
> +There is a process and code in place to help with SolidOS releases. However, we would like to get better and automate as much as possible. Open issues can be found on the [Project Board](https://gith
```suggestion
There is an existing process and codebase in place to help with SolidOS releases. However, we would like to get better and automate as much as possible. Open issues can be found on the [Project Board](https://github.com/orgs/SolidOS/projects/1/views/4) under the CI category.
```

2022-04-26 14:39 UTC, TallTed commented on README.md
> +_**Note:** It might prompt you to install a dedicated node version, somthing like `nvm install xxx # version missing mentioned in console log`._
```suggestion
_**Note:** It might prompt you to install a specific `node` version, something like `nvm install xxx # version missing mentioned in console log`._
```

2022-04-26 14:40 UTC, TallTed commented on README.md
> +_**Note:** In case of errors try to follow what the output messages (errors) suggest in the console to fix the problems. And write us up on [SolidOS team chat](https://gitter.im/solid/solidos)._
```suggestion
_**Note:** In case of errors, try to follow what the output messages (errors) suggest in the console to fix the problems, and let us know on the [SolidOS team chat](https://gitter.im/solid/solidos)._
```

2022-04-26 14:42 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +- In any given branch/PR there should be no more than a couple files modified. Try to stick to one, however for tests you may need two - one for the test and one for the code you are testing.
```suggestion
- In any given branch/PR, there should be no more than a couple files modified. In general, try to stick to one, though you may need two for testing — one for the test, and one for the code you are testing.
```

2022-04-26 14:43 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +- PR naming: add **WIP** in the title of the PR if you want a review.
```suggestion
- include **WIP** in the title of the PR if you want a review.
```

2022-04-26 14:43 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +In general, if the code is clean it is easy to understand the algorithm but sometimes it makes sense to add comments to explain or give an example.
```suggestion
In general, if the code is clean, it is easy to understand the algorithm, but sometimes it may make sense to include comments to explain or give an example.
```

2022-04-26 14:43 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +Comment blocks look:
```suggestion
Comment blocks look like this:
```

2022-04-26 14:44 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> + One-line comments look like:
```suggestion
 One-line comments look like this:
```

2022-04-26 14:44 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> + */
```suggestion
  doSomething()
```

2022-04-26 14:45 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> + */
```suggestion
 */
   doSomething()
```

2022-04-26 14:47 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +An example when you need a TODO is when you refactor code. There will be times you run across code that cannot be easily changed or may be better suited for an alternate branch. In this case you can:
```suggestion
An example of when you need a TODO is when you refactor code. There may be times you run across code that cannot be easily changed or that may be better suited for an alternate branch. In this case you can:
```

2022-04-26 14:48 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +   `/* @@ TODO comment about what needs to be done and/or why it is a problem, see [link to issue]`
```suggestion
2. Document the code with a comment such as that shown below
   `/* @@ TODO [comment about what needs to be done and/or why it is a problem]. See [link to issue]`
```

2022-04-26 14:49 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +2. Add types to public methods (if this is dificult you can add the 'any' type and add comments as described above to indicate it needs further work)
```suggestion
1. Rename file to `.ts`
2. Add types to public methods (if this is difficult, you can add the `any` type and add comments as described above to indicate it needs further work)
```

2022-04-26 14:49 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +4. No Logic changes, only minor refactoring
```suggestion
4. No Logic changes; only minor refactoring
```

2022-04-26 14:51 UTC, TallTed commented on documentation/guidelines/coding_guidelines.md
> +Need to run builds using bash because of sh command.
```suggestion
Notes: Single quotes can't be used in scripts on Windows; need to use `\"` instead.
Builds must be run using `bash`, because of `sh` command.
```

2022-04-26 14:51 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +This document talks about SolidOS stack Node versions and about work required upon release, in particular about dependency upgrades.
```suggestion
This document talks about SolidOS stack Node versions, and about work required upon release; in particular, about dependency upgrades.
```

2022-04-26 14:51 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +Table of content:
```suggestion
Table of contents:
```

2022-04-26 14:54 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +However since all SolidOS stack is build into the mashlib.js at the ned -> the Node version used is not that important (still best practice to so do it so).
```suggestion
Local development should be built with the latest used Node version. One can make sure this is the case by running `nvm use` in the root of the repo. This command will look for a file named `.nvmrc`, and use the node version specified therein.
Since the whole SolidOS stack is built into the `mashlib.js` at the end, the Node version used is not vitally important, but best practice is still to so do it so.
```

2022-04-26 14:58 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +- change the officially development supported Node version on SolidOS stack mentioned in `.nvmrc`. The `.nvmrc` file is available on each repo, [for example on SolidOS repo](https://github.com/solid/
```suggestion
- change the Node version in CI of each affected SolidOS repo (including `release.yml` if available)
  - ensure the published node version in CI is at least one version earlier than latest release, but make sure it is still in LTS by checking the [Node Releases](https://nodejs.org/en/about/releases/)
- update the officially supported development Node version on SolidOS stack mentioned in `.nvmrc`. The `.nvmrc` file is available on each repo, [for example on SolidOS repo](https://github.com/solid/solidos/blob/main/.nvmrc).
```

2022-04-26 15:02 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +***Note:*** Given a version number MAJOR.MINOR.PATCH of a repository, increment the:
```suggestion
***Note:*** Our work follows the [Semantic Versioning practices](https://semver.org/) in which, given a version number `MAJOR.MINOR.PATCH` of a repository, increment the:
```

2022-04-26 15:06 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +- it is also good to run a `npm audit` from time to time and run a `npm audit fix --force`
```suggestion
- it is also good to run an `npm audit` from time to time, and run a `npm audit fix --force` as needed
```

2022-04-26 15:11 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +- build must follow a strict order becaused repositories depend on eachother. The priority is as follows:
```suggestion
- In each repository to be released, you need to do a dependency upgrade with `npx npm-check-updates -u`. This upgrades all dependencies to major versions. Afterwards, you need to make sure the repo builds and all tests pass.
- The `main` branch of each repository should be green in GitHub CI.
- The build must follow a strict order because the repositories depend on each other. The priority is as follows:
```

2022-04-26 15:14 UTC, TallTed commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +***Note:*** The strict build order means for example, if you do a change in `solid-ui`, all following panes that make use of the `solid-ui` changes need to be also upgraded. And then `solid-panes` ne
```suggestion
  1. rdflib
  1. solid-logic
  1. solid-ui
  1. activitystreams-pane
  1. chat-pane
  1. contacts-pane
  1. folder-pane
  1. issue-pane
  1. meeting-pane
  1. profile-pane
  1. source-pane
  1. solid-panes
  1. mashlib
  1. NSS
  1. solidos
  ***Note:*** The strict build order means, for example, if you make a change in `solid-ui`, all the following panes that make use of the `solid-ui` changes also need to be upgraded; then `solid-panes` must be upgraded to contain the new `solid-ui` version, and because `solid-panes` version changes, the `mashlib` version also needs to change.
```

2022-04-26 15:15 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +Tbale of content:
```suggestion
Table of contents:
```

2022-04-26 15:17 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +- Tests should be in a dedicated folder called 'test' in the whole SolidOS stack.
```suggestion
- When you fix a bug, start by creating a test to reproduce it, and then fix it.
- Tests throughout the SolidOS stack should be in dedicated folders called 'test'.
```

2022-04-26 15:28 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +- Add rdflib to the list of repos to be tested.
```suggestion
- At first, we will work to have more integration tests, as it is currently hard to write unit tests. As time goes on, it will eventually flip. At the same time, we will refactor code to be more modular to do unit tests.
- Both unit tests and integration tests will be in all repos.
- No end-to-end (e2e) tests currently; we may do some of these outside of the repos.
- Add `rdflib` to the list of repos to be tested.
```

2022-04-26 15:30 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +The original code was not written with testing in mind. In order to make testing more efficient you may find it easier to export a function. To do this include the following comment above the functio
```suggestion
The original code was not written with testing in mind. To make testing more efficient, you may find it easier to export a function. To do this, include the following comment above the function so that it does not get picked up by `Typedoc`.
```

2022-04-26 15:40 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +` \* @@ TODO and desribe the problem.
```suggestion
In this case, follow the commenting procedures in the Code `Readme.md`, which is to add the comment
` \* @@ TODO` and describe the problem.
```

2022-04-26 15:41 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +You can reference <https://github.com/solidos/solid-ui/issues/215> in your [TODO comment](./coding_guidelines.md#adding-a-todo) if the code is hard to test due to DOM manipulation.
```suggestion
You can reference <https://github.com/solidos/solid-ui/issues/215> in your [`TODO` comment](./coding_guidelines.md#adding-a-todo) if the code is hard to test due to DOM manipulation.
```

2022-04-26 15:41 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +unit test to set up some data in the store. Don't forget to [clearStore afterEach](https://github.com/solidos/solid-ui/blob/5fd8fb0/test/unit/widgets/buttons.test.ts#L214).
```suggestion
unit test to set up some data in the store. Don't forget to [`clearStore afterEach`](https://github.com/solidos/solid-ui/blob/5fd8fb0/test/unit/widgets/buttons.test.ts#L214).
```

2022-04-26 15:42 UTC, TallTed commented on documentation/guidelines/testing_guidelines.md
> +- `expect(A).toEqualGraph(B)`: Use this matcher to check whether graphs A and B are equal (meaning containing the
```suggestion
- `expect(A).toEqualGraph(B)`: Use this matcher to check whether graphs A and B are equal (meaning they contain the
```

2022-04-27 08:43 UTC, timea-solid commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +***Note:*** The strict build order means for example, if you do a change in `solid-ui`, all following panes that make use of the `solid-ui` changes need to be also upgraded. And then `solid-panes` ne
Will try to improve it without the 1. in front of each enumeration.

2022-04-27 08:43 UTC, timea-solid commented
Thank you @TallTed !

2022-04-27 08:45 UTC, timea-solid commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +***Note:*** The strict build order means for example, if you do a change in `solid-ui`, all following panes that make use of the `solid-ui` changes need to be also upgraded. And then `solid-panes` ne
```suggestion
 _**Note:** The strict build order means, for example, if you make a change in `solid-ui`, all the following panes that make use of the `solid-ui` changes also need to be upgraded; then `solid-panes` must be upgraded to contain the new `solid-ui` version, and because `solid-panes` version changes, the `mashlib` version also needs to change._
```

2022-04-27 17:30 UTC, angelo-v commented on documentation/guidelines/coding_guidelines.md
> +Comment blocks look like this:
This is just the normal way one does comments in typescript, I do not think we need to explain it here

2022-04-27 17:30 UTC, angelo-v commented on documentation/guidelines/coding_guidelines.md
> +
Perhaps add a sentence that we want to migrate everything to typescript in the long run

2022-04-27 17:30 UTC, angelo-v commented on documentation/guidelines/coding_guidelines.md
> +3. Add comments
about what?

2022-04-27 17:30 UTC, angelo-v commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +- it is also good to run an `npm audit` from time to time, and run a `npm audit fix --force` as needed
I think `--force` should be used with care and usually you do just `npm audit fix`

2022-04-27 17:30 UTC, angelo-v commented on documentation/guidelines/testing_guidelines.md
> +The original code was not written with testing in mind. To make testing more efficient, you may find it easier to export a function. To do this, include the following comment above the function so th
I do not agree with that. You do not just extract a method just to make testing easier. You have to extract a useful/meaningful piece of functionality, which also could be documented with typedoc then

2022-04-28 07:58 UTC, timea-solid commented on documentation/guidelines/coding_guidelines.md
> +
```suggestion

One of the long-term goals of the SolidOS stack is to convert the code in TypeScript.

```

2022-04-28 07:58 UTC, timea-solid commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +- it is also good to run an `npm audit` from time to time, and run a `npm audit fix --force` as needed
```suggestion
- it is also good to run an `npm audit` from time to time, and run a `npm audit fix` as needed
```

2022-04-28 07:58 UTC, timea-solid commented on documentation/guidelines/coding_guidelines.md
> +3. Add comments
```suggestion
3. Add a comment that the file was previously javascript
```

2022-07-21 20:32 UTC, timbl requested changes
Apart from version 1.0.0 comment, looks good to me

2022-07-21 20:32 UTC, timbl commented on documentation/guidelines/dependencies_and_release_guidelines.md
> +
Add: To avoid the strange and different way semantic versioning works with version 0.x.x, please start a new module at version `1.0.0`.  There is no magic associated with "The Version 1.0 release". It is just a version. In the early days, there may be many incompatible changes, so you may get to version `6.0.0` soon. That's ok, you have tracked the changes accurately.

2022-08-23 07:01 UTC, merged